"""update resume metadata

Revision ID: 77595241f1f3
Revises: 39d83f78828a
Create Date: 2026-07-06 14:37:46.630433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77595241f1f3'
down_revision: Union[str, None] = '39d83f78828a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('original_filename', sa.String(), nullable=False))
    op.add_column('resumes', sa.Column('stored_filename', sa.String(), nullable=False))
    op.add_column('resumes', sa.Column('file_size', sa.BigInteger(), nullable=False))
    op.add_column('resumes', sa.Column('mime_type', sa.String(), nullable=False))
    op.alter_column('resumes', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(
    "uq_resumes_stored_filename",
    "resumes",
    ["stored_filename"],
)
    op.drop_column('resumes', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(
    "uq_resumes_stored_filename",
    "resumes",
    type_="unique",
)
    op.alter_column('resumes', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('resumes', 'mime_type')
    op.drop_column('resumes', 'file_size')
    op.drop_column('resumes', 'stored_filename')
    op.drop_column('resumes', 'original_filename')
    # ### end Alembic commands ###
