"""add resume parsing metadata

Revision ID: 94c35128720f
Revises: 77595241f1f3
Create Date: 2026-07-10 16:51:00.822351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c35128720f'
down_revision: Union[str, None] = '77595241f1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('parsing_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('resumes', sa.Column('parsing_error', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'parsed_at')
    op.drop_column('resumes', 'parsing_error')
    op.drop_column('resumes', 'parsing_status')
    op.drop_column('resumes', 'extracted_text')
    # ### end Alembic commands ###
